export const WINDOW_WIDTH_SMALL = 576;

export const WINDOW_WIDTH_MEDIUM = 768;

export const WINDOW_WIDTH_LARGE = 992;

export const WINDOW_WIDTH_EXTRA_LARGE = 1200;

export const WINDOW_WIDTH_DESKTOP_LARGE = 1366;
